//
//  Utils.swift
//  FlowerSnap
//
//  Created by 陆依鸣 on 2018/11/16.
//  Copyright © 2018 陆依鸣. All rights reserved.
//

import UIKit

let index2name = [
    0: "anthurium",
    1: "artichoke",
    2: "azalea",
    3: "balloon flower",
    4: "bee balm",
    5: "bird of paradise",
    6: "blackberry lily",
    7: "blanket flower",
    8: "bluebell",
    9: "bolero deep blue",
    10: "bougainvillea",
    11: "buttercup",
    12: "californian poppy",
    13: "camellia",
    14: "canna lily",
    15: "canterbury bells",
    16: "carnation",
    17: "cautleya spicata",
    18: "clematis",
    19: "corn poppy",
    20: "cowslip",
    21: "crocus",
    22: "cyclamen",
    23: "daffodil",
    24: "daisy",
    25: "dandelion",
    26: "desert-rose",
    27: "foxglove",
    28: "frangipani",
    29: "fritillary",
    30: "garden phlox",
    31: "gaura",
    32: "gazania",
    33: "geranium",
    34: "giant white arum lily",
    35: "globe thistle",
    36: "globe-flower",
    37: "grape hyacinth",
    38: "hard-leaved pocket orchid",
    39: "hibiscus",
    40: "hippeastrum",
    41: "iris",
    42: "japanese anemone",
    43: "lenten rose",
    44: "lotus",
    45: "magnolia",
    46: "marigold",
    47: "mexican aster",
    48: "mexican petunia",
    49: "monkshood",
    50: "osteospermum",
    51: "oxeye daisy",
    52: "pansy",
    53: "passion flower",
    54: "pelargonium",
    55: "petunia",
    56: "poinsettia",
    57: "primula",
    58: "purple coneflower",
    59: "red ginger",
    60: "rose",
    61: "snapdragon",
    62: "snowdrop",
    63: "spring crocus",
    64: "stemless gentian",
    65: "sunflower",
    66: "sweet pea",
    67: "sweet william",
    68: "sword lily",
    69: "thorn apple",
    70: "tigerlily",
    71: "toad lily",
    72: "trumpet creeper",
    73: "tulip",
    74: "water lily",
    75: "watercress",
    76: "windflower",
    77: "梅花",
    78: "腊梅花"
]

let index2chn: [Int: String] = [
    0: "花烛属",
    1: "菜薊",
    2: "杜鹃花",
    3: "桔梗",
    4: "美國薄荷屬",
    5: "鹤望兰",
    6: "射干",
    7: "天人菊",
    8: "蓝风铃草",
    9: "洋桔梗",
    10: "九重葛属",
    11: "金凤花",
    12: "花菱草",
    13: "山茶属",
    14: "美人蕉屬",
    15: "彩钟花",
    16: "康乃馨",
    17: "红苞距药姜",
    18: "铁线莲属",
    19: "虞美人",
    20: "黄花九轮草",
    21: "番红花",
    22: "仙客來屬",
    23: "黄水仙（喇叭水仙）",
    24: "雏菊",
    25: "蒲公英（黄花地丁）",
    26: "沙漠玫瑰",
    27: "毛地黄属",
    28: "緬梔花",
    29: "贝母",
    30: "天蓝绣球",
    31: "山桃草属",
    32: "勋章菊",
    33: "老鸛草屬",
    34: "马蹄莲",
    35: "蓝刺头属",
    36: "金蓮花屬",
    37: "葡萄风信子属",
    38: "硬叶兜兰",
    39: "木槿属",
    40: "孤挺花（朱顶红）",
    41: "鸢尾花",
    42: "打破碗花花",
    43: "鐵筷子屬",
    44: "荷花",
    45: "木兰花",
    46: "万寿菊（金盏花）",
    47: "大波斯菊",
    48: "紫花芦莉草",
    49: "乌头属",
    50: "藍眼菊",
    51: "法蘭西菊",
    52: "三色堇",
    53: "西番蓮屬",
    54: "天竺葵属",
    55: "碧冬茄属",
    56: "一品紅",
    57: "報春花屬",
    58: "松果菊",
    59: "紅花月桃",
    60: "玫瑰（蔷薇)",
    61: "金鱼草属",
    62: "雪莲花",
    63: "荷蘭番紅花",
    64: "无茎龙胆花",
    65: "向日葵",
    66: "香碗豆",
    67: "须苞石竹",
    68: "唐菖蒲属",
    69: "曼陀罗花",
    70: "虎皮百合（卷丹）",
    71: "油点草属",
    72: "厚萼凌霄",
    73: "郁金香",
    74: "睡莲",
    75: "西洋菜",
    76: "栎木银莲花",
    77: "梅花",
    78: "腊梅花"
]

let index2sci: [Int: String] = [
    0: "Anthurium",
    1: "Artichoke",
    2: "Rhododendron",
    3: "Platycodon",
    4: "Monarda",
    5: "Strelitzia",
    6: "Iris domestica",
    7: "Gaillardia",
    8: "Hyacinthoides",
    9: "Eustoma russellianum",
    10: "Bougainvillea",
    11: "Ranunculus",
    12: "Eschscholzia californica",
    13: "Camellia",
    14: "Canna (plant)",
    15: "Campanula medium",
    16: "Dianthus caryophyllus",
    17: "Cautleya spicata",
    18: "Clematis",
    19: "Papaver rhoeas",
    20: "Primula veris",
    21: "Crocus",
    22: "Cyclamen",
    23: "Narcissus (plant)",
    24: "Bellis perennis",
    25: "Taraxacum",
    26: "Adenium",
    27: "Digitalis",
    28: "Plumeria",
    29: "Fritillaria",
    30: "Phlox paniculata",
    31: "Gaura",
    32: "Gazania",
    33: "Geranium",
    34: "Zantedeschia aethiopica",
    35: "Echinops",
    36: "Trollius",
    37: "Muscari",
    38: "Paphiopedilum micranthum",
    39: "Hibiscus",
    40: "Hippeastrum",
    41: "Iris (plant)",
    42: "Anemone hupehensis",
    43: "Hellebore",
    44: "Nelumbo nucifera",
    45: "Magnolia",
    46: "Tagetes",
    47: "Cosmos bipinnatus",
    48: "Ruellia simplex",
    49: "Aconitum",
    50: "Osteospermum",
    51: "Leucanthemum vulgare",
    52: "Pansy",
    53: "Passiflora",
    54: "Pelargonium",
    55: "Petunia",
    56: "Poinsettia",
    57: "Primula",
    58: "Echinacea purpurea",
    59: "Alpinia purpurata",
    60: "Rose",
    61: "Antirrhinum",
    62: "Galanthus",
    63: "Crocus vernus",
    64: "Gentiana acaulis",
    65: "Helianthus",
    66: "Sweet pea",
    67: "Dianthus barbatus",
    68: "Gladiolus",
    69: "Datura stramonium",
    70: "Lilium lancifolium",
    71: "Tricyrtis",
    72: "Campsis radicans",
    73: "Tulip",
    74: "Nymphaeaceae",
    75: "Watercress",
    76: "Anemone nemorosa",
    77: "Prunus mume",
    78: "Chimonanthuse"
]

let index2image: [Int: UIImage] = [
    0: UIImage(named: "anthurium.jpg")!,
    1: UIImage(named: "artichoke.jpg")!,
    2: UIImage(named: "azalea.jpg")!,
    3: UIImage(named: "balloon flower.jpg")!,
    4: UIImage(named: "bee balm.jpg")!,
    5: UIImage(named: "bird of paradise.jpg")!,
    6: UIImage(named: "blackberry lily.jpg")!,
    7: UIImage(named: "blanket flower.jpg")!,
    8: UIImage(named: "bluebell.jpg")!,
    9: UIImage(named: "bolero deep blue.jpg")!,
    10: UIImage(named: "bougainvillea.jpg")!,
    11: UIImage(named: "buttercup.jpg")!,
    12: UIImage(named: "californian poppy.jpg")!,
    13: UIImage(named: "camellia.jpg")!,
    14: UIImage(named: "canna lily.jpg")!,
    15: UIImage(named: "canterbury bells.jpg")!,
    16: UIImage(named: "carnation.jpg")!,
    17: UIImage(named: "cautleya spicata.jpg")!,
    18: UIImage(named: "clematis.jpg")!,
    19: UIImage(named: "corn poppy.jpg")!,
    20: UIImage(named: "cowslip.jpg")!,
    21: UIImage(named: "crocus.jpg")!,
    22: UIImage(named: "cyclamen.jpg")!,
    23: UIImage(named: "daffodil.jpg")!,
    24: UIImage(named: "daisy.jpg")!,
    25: UIImage(named: "dandelion.jpg")!,
    26: UIImage(named: "desert-rose.jpg")!,
    27: UIImage(named: "foxglove.jpg")!,
    28: UIImage(named: "frangipani.jpg")!,
    29: UIImage(named: "fritillary.jpg")!,
    30: UIImage(named: "garden phlox.jpg")!,
    31: UIImage(named: "gaura.jpg")!,
    32: UIImage(named: "gazania.jpg")!,
    33: UIImage(named: "geranium.jpg")!,
    34: UIImage(named: "giant white arum lily.jpg")!,
    35: UIImage(named: "globe thistle.jpg")!,
    36: UIImage(named: "globe-flower.jpg")!,
    37: UIImage(named: "grape hyacinth.jpg")!,
    38: UIImage(named: "hard-leaved pocket orchid.jpg")!,
    39: UIImage(named: "hibiscus.jpg")!,
    40: UIImage(named: "hippeastrum.jpg")!,
    41: UIImage(named: "iris.jpg")!,
    42: UIImage(named: "japanese anemone.jpg")!,
    43: UIImage(named: "lenten rose.jpg")!,
    44: UIImage(named: "lotus.jpg")!,
    45: UIImage(named: "magnolia.jpg")!,
    46: UIImage(named: "marigold.jpg")!,
    47: UIImage(named: "mexican aster.jpg")!,
    48: UIImage(named: "mexican petunia.jpg")!,
    49: UIImage(named: "monkshood.jpg")!,
    50: UIImage(named: "osteospermum.jpg")!,
    51: UIImage(named: "oxeye daisy.jpg")!,
    52: UIImage(named: "pansy.jpg")!,
    53: UIImage(named: "passion flower.jpg")!,
    54: UIImage(named: "pelargonium.jpg")!,
    55: UIImage(named: "petunia.jpg")!,
    56: UIImage(named: "poinsettia.jpg")!,
    57: UIImage(named: "primula.jpg")!,
    58: UIImage(named: "purple coneflower.jpg")!,
    59: UIImage(named: "red ginger.jpg")!,
    60: UIImage(named: "rose.jpg")!,
    61: UIImage(named: "snapdragon.jpg")!,
    62: UIImage(named: "snowdrop.jpg")!,
    63: UIImage(named: "spring crocus.jpg")!,
    64: UIImage(named: "stemless gentian.jpg")!,
    65: UIImage(named: "sunflower.jpg")!,
    66: UIImage(named: "sweet pea.jpg")!,
    67: UIImage(named: "sweet william.jpg")!,
    68: UIImage(named: "sword lily.jpg")!,
    69: UIImage(named: "thorn apple.jpg")!,
    70: UIImage(named: "tigerlily.jpg")!,
    71: UIImage(named: "toad lily.jpg")!,
    72: UIImage(named: "trumpet creeper.jpg")!,
    73: UIImage(named: "tulip.jpg")!,
    74: UIImage(named: "water lily.jpg")!,
    75: UIImage(named: "watercress.jpg")!,
    76: UIImage(named: "windflower.jpg")!,
    77: UIImage(named: "梅花.jpg")!,
    78: UIImage(named: "腊梅花.jpg")!,
]
